Add keyword extraction logic and rename source text collector directory
Police-Data-Accessibility-Project/data-source-identification pull request #58
Opened 2024-03-24 23:39 UTC by maxachis

#### Fixes

Nothing, but partially addresses #55 

#### Description

* Renames html_tag_collector directory (and associated references) to source_tag_collector
* Create KeywordExtractor, a tool that utilizes the KeyBERT library to extract keywords from a web page's html

#### Testing

* A unit test has been created in test_source_text_collector_unit.py, which can be run to demonstrate basic functionality of the added method
* The integration test in test_source_text_collector_integration.py can be run on the given urls (or others) to see how the keywords appear alongside other included elements

2024-03-25 16:13 UTC, josh-chamberlain reviewed
If we pass `keywords` as a property, it's not clear how it was generated—I would prefer to declare `bert_keywords` (in whatever case) since it's likely we'll have other kinds of keywords in the future (people love labeling stuff). Otherwise, this looks like a worthy enhancement / worth a try to see how much more fidelity we get

2024-03-25 16:13 UTC, josh-chamberlain commented on source_text_collector/keyword_extractor.py
> +from keybert import KeyBERT
do we need this in the requirements.txt?

2024-03-25 16:15 UTC, josh-chamberlain commented
@EvilDrPurple would you want to test this one / leave your review?

2024-03-25 18:11 UTC, EvilDrPurple commented
I tested it and looks very good. One thing I should note is it took about 10 minutes to execute for 18 urls, meaning it will take approximately 37 hours to run on our current list of over 4000 urls. Perhaps we could add an option to disable the keyword extractor, sort of like how it's done with the render-javascript feature. This way when we don't need the keywords generated we don't have to wait a very long time to get the tags.

2024-03-25 18:14 UTC, EvilDrPurple requested changes
I tested it and looks very good. One thing I should note is it took about 10 minutes to execute for 18 urls, meaning it will take approximately 37 hours to run on our current list of over 4000 urls. Perhaps we could have the keyword extraction disabled by default, sort of like how it's done with the render-javascript feature. This way when we don't need the keywords generated we don't have to wait a very long time to get the tags.

2024-03-26 22:13 UTC, maxachis commented
> I tested it and looks very good. One thing I should note is it took about 10 minutes to execute for 18 urls, meaning it will take approximately 37 hours to run on our current list of over 4000 urls. Perhaps we could have the keyword extraction disabled by default, sort of like how it's done with the render-javascript feature. This way when we don't need the keywords generated we don't have to wait a very long time to get the tags.

I may like to take a second look at how I'm implementing it -- considering the model is pre-trained, in theory labeling shouldn't take so long after the initial download of the model. 

I may also need to think about how to test it to account for the sort of hardware we would run it on, as I may get faster run times because of my personal hardware which could bias my assessment of its performance in the cloud. 

I also confess that I had tested it primarily for functionality and not performance, which is worthwhile for me to take into consideration. Relatedly, @josh-chamberlain, I wonder if the [PR template](https://github.com/Police-Data-Accessibility-Project/docs/blob/main/meta/operations/staff/github-pull-request-template.md) might benefit from the inclusion of a header called "Performance Impacts" or something similar, to encourage disclosing how a change impacts execution time and other metrics.

2024-03-27 20:36 UTC, maxachis commented
@josh-chamberlain In terms of implementation, I see several possible options. There are others, but these stand out to me as most apparent:

## Option 1: Inclusion in source_text_collector.py, under all conditions 

### Pros

* Code is already designed for that, so minimal alterations would be required
* Ensures consistent output in data

### Cons

* Permanently increases execution time of source_test_collector.py
* Impact of keywordization may be variable, depending on data -- for web pages with little code in expected structures, keywords may improve overall quality of data. For web pages that already have a lot of content, keywords may not add much

## Option 2: Inclusion in source_text_collector.py, under select conditions

### Pros

* Enables greater flexibility in when to apply, enabling saving time on data that is unlikely to require it
* Dynamic application of keywordization can potentially equalize quality between high-content and low-content web pages. 

### Cons

* Will require modifications to setup, both for obtaining metrics to determine when to apply keywordization and the conditional logic to execute it
* Dataset becomes more inconsistent -- some rows may have data columns which others lack, which could have unpredictable effects on performance.

## Option 3: Implement at separate, later point in pipeline

### Pros

* Decouples keywordization from other parts of process, enabling greater testability and the ability to more easily disable its functionality if the need arises
* Enables keywordization to be implemented at a separate time from other parts of pipeline, improving flexibility and possibly resilience to failure (i.e. if keywordization fails, the rest of source_text_collector.py won't be halted)

### Cons

* Data for keywordization will either need to be saved for execution (using extra storage space) or re-retrieved when performing keywordization (increasing execution cost as opposed to including it within the other code.
* Will require more substantial revamping of code, as well as clarification on where to include the code

2024-03-28 15:57 UTC, josh-chamberlain commented
@maxachis got it, so we're adding 5.5 seconds per URL on your machine. As a basis for comparison, how long does each URL take on your machine _without_ adding keywords?

Either way, I would probably recommend we test whether adding keywords improves accuracy before merging this. Hard to know whether it's worth it otherwise

2024-04-08 14:30 UTC, maxachis commented
@bonjarlow Per your discussion in the last working meeting about how removing the URLs seems to have a negative impact on accuracy, have you looked at how keywords impact accuracy when URLs are removed from the picture?

2024-04-10 21:06 UTC, bonjarlow commented
@maxachis yeah I've played around with different combinations of features,  it seems the model tops out at ~70% with or without keywords. I'll make an issue now

2024-04-11 11:37 UTC, maxachis commented
For additional clarity, the issue in question is #75

2024-04-21 22:08 UTC, maxachis commented
@bonjarlow @EvilDrPurple Coming back to this: What are your thoughts on including this keyword extraction as a part of the tag collector function? Is this useful/potentially useful enough to include?

2024-05-14 17:35 UTC, josh-chamberlain commented
@maxachis What if we _only_ generate_ keywords from the human-annotated data? We'd have fewer URLs, guaranteed to be used for training. I think we could use those keywords to scope common crawl or otherwise generate better batches, too.

2024-05-14 20:04 UTC, maxachis commented
> @maxachis What if we _only generate keywords from the human-annotated data_? We'd have fewer URLs, guaranteed to be used for training. I think we could use those keywords to scope common crawl or otherwise generate better batches, too.

@josh-chamberlain I'm intrigued by these thoughts, but I'm unclear on how the process would work. Does this mean that humans come up with the keywords, or that we apply automated keyword generation to only human-annotated data? Or some fancy third option?

2024-05-22 01:17 UTC, maxachis commented
> @maxachis we could ask people for keywords, but I was thinking it would work the same way you had in mind—except only applied to annotated sources. It's a way to worry about a lot fewer keywords with _maybe_ better quality.
> 
> It does mean more editing data mid-stream...we'd have to get really good at modifying label studio / hugging face data in a sensible way.

With that in mind, I'm wondering if this PR is ready for prime-time, or if it might need some adjustments. Because as of right now it's designed to pull keywords from everything being pulled.

2024-05-22 02:52 UTC, josh-chamberlain commented
@maxachis yeah, I just updated #49 to mention it. I think we should only do it for labeled sources; we could also generate descriptions at the same time.

2025-04-18 11:58 UTC, maxachis commented
Closing because this is ooooolllllldddd

2025-04-18 11:58 UTC, closed without merging